import Flutter
import Foundation
import Darwin  // pipe, dup, dup2, read, close, STDOUT_FILENO, STDERR_FILENO

// WasmSandboxHandler — iOS implementation of the ai.flutterclaw/sandbox MethodChannel.
//
// Architecture:
//   WAMR interpreter (Apache 2.0)
//     └─ TinyEMU-c2w (MIT)  — RISC-V64 CPU emulator compiled to Wasm
//          └─ Linux 6.1 kernel (custom, CONFIG_RISCV_SBI_V01=y)
//               └─ Alpine 3.21 userspace (python3, pip, git, curl, wget, jq, bash, file)
//
// Limitations vs Android:
//   - No internet in guest VM (WAMR networking WIP) → apk add online fails
//   - Packages fixed at image build time (pre-installed: python3, pip, git, curl, wget, jq, bash, file)
//   - ~10–100× slower than Android (RISC-V emulation on ARM64 hardware)
//   - riscv64 architecture (`uname -m` → riscv64)
//   - Single-core CPU (no SMP)
//
// WAMR integration:
//   WAMR is integrated via its C API through a bridging header (Runner-Bridging-Header.h).
//   The xcframework lives at ios/WAMR/wamr.xcframework.
//   sandbox_exec calls wasm_runtime_init(), loads the Wasm module, sets --dir for file
//   sharing, and communicates with TinyEMU via the virtio serial console (stdin/stdout
//   of the Wasm instance).

class WasmSandboxHandler {

    // URL and SHA256 of the pre-built Wasm artefact.
    // Generated by scripts/ios-sandbox/build.sh or the build-ios-sandbox CI workflow.
    // Update both when publishing a new image version via GitHub release.
    static let wasmDownloadURL = "https://github.com/flutterclaw/flutterclaw/releases/download/ios-sandbox%2Fv3.21.0-1/alpine-ios-sandbox.initialized.wasm"
    static let wasmSHA256 = "8bf66d9b7702ae97bd60f97637b305ca1791a77168fe851b1af8bc2e28bb2ff8"
    static let wasmVersion = "3.21.0-1"

    private let channel: FlutterMethodChannel

    init(messenger: FlutterBinaryMessenger) {
        channel = FlutterMethodChannel(
            name: "ai.flutterclaw/sandbox",
            binaryMessenger: messenger
        )
        channel.setMethodCallHandler { [weak self] call, result in
            self?.handleMethodCall(call, result: result)
        }
    }

    private func handleMethodCall(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "sandbox_status":
            handleStatus(result: result)
        case "sandbox_setup":
            handleSetup(result: result)
        case "sandbox_exec":
            handleExec(call: call, result: result)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // MARK: - sandbox_status

    private func handleStatus(result: @escaping FlutterResult) {
        let wasmURL = wasmFileURL()
        let wasmReady = FileManager.default.fileExists(atPath: wasmURL.path)
        let sharedPath = sharedDirectoryURL().path

        result([
            "ready": wasmReady,
            "platform": "ios",
            "emulator": "tinyemu-riscv64",
            "network": false,
            "wasm_version": Self.wasmVersion,
            "shared_path": sharedPath,
            "root_path": rootPersistenceDirectoryURL().path,
            "proot_available": false,
            "rootfs_available": wasmReady,
            "note": wasmReady
                ? "Alpine 3.21 (riscv64 emulated). No internet in VM. Pre-installed: python3, pip, git, curl, wget, jq, bash, file."
                : "Call sandbox_setup to download the Alpine Wasm image (~100-120 MB).",
        ] as [String: Any])
    }

    // MARK: - sandbox_setup

    private func handleSetup(result: @escaping FlutterResult) {
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            do {
                try self.provision()
                DispatchQueue.main.async {
                    result(["ready": true, "platform": "ios"])
                }
            } catch {
                DispatchQueue.main.async {
                    result(["error": true, "message": error.localizedDescription])
                }
            }
        }
    }

    // Idempotent: skips download if the Wasm file already exists with the
    // correct version marker. Creates the shared directory regardless.
    private func provision() throws {
        let fm = FileManager.default
        let sandboxDir = sandboxDirectoryURL()
        let sharedDir = sharedDirectoryURL()
        let wasmFile = wasmFileURL()
        let versionFile = sandboxDir.appendingPathComponent(".wasm_version")

        // Create sandbox, shared, and persistent root directories.
        try fm.createDirectory(at: sandboxDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: sharedDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: rootPersistenceDirectoryURL(), withIntermediateDirectories: true)

        // Check if existing Wasm matches current version.
        if fm.fileExists(atPath: wasmFile.path),
           let storedVersion = try? String(contentsOf: versionFile, encoding: .utf8),
           storedVersion.trimmingCharacters(in: .whitespacesAndNewlines) == Self.wasmVersion {
            return  // Already provisioned and up to date.
        }

        // Remove stale Wasm if present.
        if fm.fileExists(atPath: wasmFile.path) {
            try fm.removeItem(at: wasmFile)
        }

        // Download the Wasm artefact.
        guard let url = URL(string: Self.wasmDownloadURL) else {
            throw SandboxError.invalidURL
        }

        var downloadError: Error?
        var downloadedURL: URL?
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.downloadTask(with: url) { tmpURL, response, error in
            defer { semaphore.signal() }
            if let error {
                downloadError = error
                return
            }
            guard let tmpURL,
                  let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                downloadError = SandboxError.downloadFailed(
                    (response as? HTTPURLResponse)?.statusCode ?? 0
                )
                return
            }
            downloadedURL = tmpURL
        }
        task.resume()
        semaphore.wait()

        if let error = downloadError { throw error }
        guard let src = downloadedURL else { throw SandboxError.downloadFailed(0) }

        try fm.moveItem(at: src, to: wasmFile)

        // Verify SHA256 if configured (skip when empty for dev convenience).
        if !Self.wasmSHA256.isEmpty {
            let data = try Data(contentsOf: wasmFile)
            let digest = sha256Hex(data)
            guard digest == Self.wasmSHA256 else {
                try? fm.removeItem(at: wasmFile)
                throw SandboxError.sha256Mismatch(expected: Self.wasmSHA256, got: digest)
            }
        }

        try Self.wasmVersion.write(to: versionFile, atomically: true, encoding: .utf8)
    }

    // MARK: - sandbox_exec

    private func handleExec(call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any],
              let command = args["command"] as? String, !command.isEmpty else {
            result(["error": true, "message": "command is required"])
            return
        }
        let timeoutMs = (args["timeout_ms"] as? Int) ?? 30_000
        let workingDir = (args["working_dir"] as? String) ?? "/root"

        let wasmFile = wasmFileURL()
        guard FileManager.default.fileExists(atPath: wasmFile.path) else {
            result(["error": true, "message": "Sandbox not provisioned. Call sandbox_setup first."])
            return
        }

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            let execResult = self.runInVM(
                command: command,
                workingDir: workingDir,
                timeoutMs: timeoutMs
            )
            DispatchQueue.main.async { result(execResult) }
        }
    }

    // Runs a shell command inside TinyEMU via WAMR.
    //
    // Persistence:
    //   The guest's /root/ is mapped to <documents>/sandbox/root/ via WAMR --dir
    //   + container2wasm's virtio-9p bind-mount mechanism. Files written to /root/
    //   inside the VM are visible on the next exec call (same as Android PRoot).
    //   The shared_path directory is also pre-opened for host <-> VM file exchange.
    //
    // Output capture:
    //   WAMR maps WASI fd 1/2 to the process's POSIX stdout/stderr.
    //   We redirect them to pipes before calling wasm_application_execute_main,
    //   then restore and drain the pipes after the call returns.
    //
    // Exit code:
    //   The command is wrapped with a sentinel echo: `echo "__EXIT_$?__"`.
    //   The sentinel is stripped from stdout and the code is extracted.
    //
    // Timeout:
    //   The Wasm call runs on a background thread. A semaphore wait with the
    //   deadline is used; on timeout, wasm_runtime_terminate() signals the VM.
    private func runInVM(command: String, workingDir: String, timeoutMs: Int) -> [String: Any] {
        let maxOutputBytes = 65_536  // matches Android SandboxHandler cap

        let sentinel = "__FLUTTERCLAW_EXIT__"
        let wrappedCommand =
            "cd \(shellEscape(workingDir)) 2>/dev/null || cd /root\n" +
            command + "\n" +
            "echo \"\(sentinel)$?\"\n"

        #if WAMR_AVAILABLE
        return wamrExec(wrappedCommand: wrappedCommand,
                        sentinel: sentinel,
                        timeoutMs: timeoutMs,
                        maxOutputBytes: maxOutputBytes)
        #else
        return [
            "error": true,
            "message": "WAMR xcframework not yet integrated. Run scripts/build-wamr-ios.sh then pod install. sandbox_setup and sandbox_status are functional.",
        ]
        #endif
    }

    #if WAMR_AVAILABLE
    private func wamrExec(wrappedCommand: String,
                          sentinel: String,
                          timeoutMs: Int,
                          maxOutputBytes: Int) -> [String: Any] {

        guard let wasmBytes = try? Data(contentsOf: wasmFileURL()) else {
            return ["error": true, "message": "Failed to read Wasm file."]
        }

        // WASI pre-opened directories.
        // container2wasm's init binary reads preopens from the WASI fd list,
        // serialises them to /mnt/wasi1/info, and bind-mounts each one inside
        // the Alpine guest at the same absolute path.
        //   <documents>/sandbox/root/   → /root   inside Alpine (persistent /root)
        //   <documents>/sandbox/shared/ → shared  inside Alpine (file exchange)
        let rootPath   = rootPersistenceDirectoryURL().path
        let sharedPath = sharedDirectoryURL().path

        // container2wasm does NOT accept commands via argv.
        // The Wasm module boots Alpine, starts /bin/sh as PID 1, and reads
        // commands from WASI stdin. We inject the command by piping it to stdin
        // before calling wasm_application_execute_main (see stdinPipe setup below).
        let argv: [String] = ["tinyemu"]
        let dirs: [String] = [rootPath, sharedPath]
        let envs: [String] = ["TERM=xterm-256color", "HOME=/root",
                               "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]

        var stdoutData = Data()
        var stderrData = Data()
        var timedOut   = false
        var loadError  = ""

        // wasm_runtime_load takes a mutable uint8_t* (it may patch the buffer).
        var mutableWasm = wasmBytes
        mutableWasm.withUnsafeMutableBytes { (rawPtr: UnsafeMutableRawBufferPointer) in
            guard let base = rawPtr.baseAddress else { loadError = "Nil Wasm buffer"; return }

            wasm_runtime_init()

            var errBuf = [CChar](repeating: 0, count: 256)
            guard let module = wasm_runtime_load(
                base.assumingMemoryBound(to: UInt8.self),
                UInt32(wasmBytes.count),
                &errBuf, UInt32(errBuf.count)
            ) else {
                loadError = String(cString: errBuf)
                return
            }
            defer { wasm_runtime_unload(module) }

            var cArgv = argv.map { strdup($0) }
            var cDirs = dirs.map { strdup($0) }
            var cEnvs = envs.map { strdup($0) }
            defer {
                cArgv.forEach { free($0) }
                cDirs.forEach { free($0) }
                cEnvs.forEach { free($0) }
            }

            // --- I/O via wasm_runtime_set_wasi_args_ex ---
            // Pass pipe fds DIRECTLY to WAMR — no dup2 needed.
            // WAMR 2.1.0 exposes wasm_runtime_set_wasi_args_ex which takes explicit
            // stdinfd/stdoutfd/stderrfd raw handles, bypassing the process's fd 0/1/2.

            // stdin: write command + close write end before WAMR starts (EOF on read).
            var inPipe = [Int32](repeating: 0, count: 2)
            pipe(&inPipe)
            let commandInput = (wrappedCommand + "\n").data(using: .utf8)!
            commandInput.withUnsafeBytes { ptr in
                _ = write(inPipe[1], ptr.baseAddress!, commandInput.count)
            }
            close(inPipe[1])  // EOF — shell exits after running the command

            // stdout/stderr: drain threads run concurrently to prevent pipe-full deadlock.
            var outPipe = [Int32](repeating: 0, count: 2)
            var errPipe = [Int32](repeating: 0, count: 2)
            pipe(&outPipe)
            pipe(&errPipe)

            // Pass pipe fds to WAMR. WAMR stores them and calls dup() on each
            // during wasm_runtime_instantiate — so fds MUST stay open until after
            // instantiate returns.
            var constDirs = cDirs.map { UnsafePointer($0) }
            var constEnvs = cEnvs.map { UnsafePointer($0) }
            cArgv.withUnsafeMutableBufferPointer { ab in
            constDirs.withUnsafeMutableBufferPointer { db in
            constEnvs.withUnsafeMutableBufferPointer { eb in
                wasm_runtime_set_wasi_args_ex(
                    module,
                    db.baseAddress, UInt32(dirs.count),
                    nil, 0,
                    eb.baseAddress, UInt32(envs.count),
                    ab.baseAddress, Int32(argv.count),
                    Int64(inPipe[0]),   // stdinfd  — read end of command pipe
                    Int64(outPipe[1]),  // stdoutfd — write end of stdout pipe
                    Int64(errPipe[1])   // stderrfd — write end of stderr pipe
                )
            }}}

            guard let instance = wasm_runtime_instantiate(
                module,
                64 * 1024,
                4 * 1024 * 1024,
                &errBuf, UInt32(errBuf.count)
            ) else {
                // instantiate failed — close our ends before returning.
                close(inPipe[0]); close(outPipe[1]); close(errPipe[1])
                close(outPipe[0]); close(errPipe[0])
                loadError = String(cString: errBuf)
                return
            }
            // Do NOT use defer for deinstantiate — see deadlock explanation below.
            // Keep outPipe[1]/errPipe[1] open while the VM runs so writes succeed.
            // Only close stdin read end now (we've already written + closed write end).
            close(inPipe[0])

            // Start drainer threads BEFORE the VM runs.
            let drainGroup = DispatchGroup()
            drainGroup.enter()
            DispatchQueue.global(qos: .utility).async {
                stdoutData = wasmDrainPipe(outPipe[0], max: maxOutputBytes)
                drainGroup.leave()
            }
            drainGroup.enter()
            DispatchQueue.global(qos: .utility).async {
                stderrData = wasmDrainPipe(errPipe[0], max: maxOutputBytes)
                drainGroup.leave()
            }

            // Run the Wasm module on its own thread so we can enforce timeout.
            let runSema = DispatchSemaphore(value: 0)
            let deadline = DispatchTime.now() + .milliseconds(timeoutMs)

            DispatchQueue.global(qos: .userInitiated).async {
                var execArgv = cArgv
                execArgv.withUnsafeMutableBufferPointer { buf in
                    wasm_application_execute_main(instance, Int32(argv.count), buf.baseAddress)
                }
                runSema.signal()
            }

            let waitResult = runSema.wait(timeout: deadline)
            if waitResult == .timedOut {
                timedOut = true
                wasm_runtime_terminate(instance)
                _ = runSema.wait(timeout: DispatchTime.now() + .seconds(5))
            }

            // Deadlock fix: deinstantiate BEFORE drainGroup.wait().
            //
            // drainGroup.wait() blocks until drain threads see EOF on outPipe[0]/errPipe[0].
            // EOF requires ALL write ends of each pipe to be closed:
            //   - outPipe[1]: our copy (closed below) + WAMR's dup'd copy (closed by deinstantiate)
            // If we called defer{deinstantiate} at scope exit (= after drainGroup.wait()),
            // drain would wait forever for EOF that only arrives after deinstantiate.
            //
            // Correct order:
            //   1. deinstantiate → WAMR closes its dup'd copies of outPipe[1]/errPipe[1]
            //   2. close our copies → both write ends now closed → EOF for drain threads
            //   3. drainGroup.wait() → drain threads finish and return data
            wasm_runtime_deinstantiate(instance)
            close(outPipe[1])
            close(errPipe[1])

            drainGroup.wait()
        }

        if !loadError.isEmpty {
            return ["error": true, "message": "WAMR load error: \(loadError)"]
        }
        if timedOut {
            return ["exit_code": -1, "stdout": "", "stderr": "Command timed out.", "timed_out": true]
        }

        var stdoutStr = String(data: stdoutData, encoding: .utf8) ?? ""
        let stderrStr = String(data: stderrData, encoding: .utf8) ?? ""

        // Extract sentinel exit code and strip it from stdout.
        var exitCode = 0
        if let range = stdoutStr.range(of: sentinel) {
            let rest = stdoutStr[range.upperBound...].trimmingCharacters(in: .whitespacesAndNewlines)
            exitCode = Int(rest.components(separatedBy: .newlines).first ?? "0") ?? 0
            stdoutStr = String(stdoutStr[..<range.lowerBound])
        }

        var out: [String: Any] = [
            "exit_code": exitCode,
            "stdout": stdoutStr,
            "stderr": stderrStr,
            "timed_out": false,
            // DEBUG — remove before merge
            "_debug_stdout_bytes": stdoutData.count,
            "_debug_stderr_bytes": stderrData.count,
            "_debug_sentinel_found": stdoutStr.isEmpty ? "no" : "yes",
            "_debug_raw_stdout_preview": String(data: stdoutData.prefix(200), encoding: .utf8) ?? "(non-utf8)",
        ]
        if stdoutData.count >= maxOutputBytes { out["stdout_truncated"] = true }
        if stderrData.count >= maxOutputBytes { out["stderr_truncated"] = true }
        return out
    }

    #endif

    private func shellEscape(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Paths

    func wasmFileURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("alpine-ios-sandbox.wasm")
    }

    func sharedDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("shared")
    }

    // Persistent /root/ for the Alpine guest.
    // Mounted via WAMR --dir + container2wasm virtio-9p at the same absolute path
    // inside the VM, so files written to /root/ inside Alpine survive across calls.
    func rootPersistenceDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("root")
    }

    func sandboxDirectoryURL() -> URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("sandbox")
    }
}

// MARK: - SHA256

import CommonCrypto

private func sha256Hex(_ data: Data) -> String {
    var digest = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
    data.withUnsafeBytes { CC_SHA256($0.baseAddress, CC_LONG(data.count), &digest) }
    return digest.map { String(format: "%02x", $0) }.joined()
}

// MARK: - Helpers

// Drain a pipe read-fd into a Data buffer, capped at `max` bytes.
// Reads until EOF (write end closed) or cap reached. Closes the fd when done.
private func wasmDrainPipe(_ fd: Int32, max: Int) -> Data {
    var data = Data()
    var buf  = [UInt8](repeating: 0, count: 4096)
    while data.count < max {
        let n = read(fd, &buf, min(buf.count, max - data.count))
        if n <= 0 { break }
        data.append(contentsOf: buf[..<n])
    }
    close(fd)
    return data
}

// MARK: - Errors

private enum SandboxError: LocalizedError {
    case invalidURL
    case downloadFailed(Int)
    case sha256Mismatch(expected: String, got: String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid Wasm download URL."
        case .downloadFailed(let code):
            return "Failed to download Alpine Wasm image (HTTP \(code))."
        case .sha256Mismatch(let expected, let got):
            return "Wasm image SHA256 mismatch. Expected \(expected), got \(got)."
        }
    }
}
