import Flutter
import Foundation
import Darwin  // pipe, read, write, close

// WasmSandboxHandler — iOS implementation of the ai.flutterclaw/sandbox MethodChannel.
//
// Runtime backends (in priority order):
//
//   1. C2WNet (wazero + gvisor-tap-vsock, gomobile xcframework):
//      Pure-Go WASM runtime with full TCP/IP networking.
//      The guest VM gets internet access via a virtual network (192.168.127.0/24).
//      Build with: scripts/build-c2wnet-ios.sh
//
//   2. WAMR (WebAssembly Micro Runtime, C xcframework):
//      Interpreter mode, no networking in the guest VM.
//      Build with: scripts/build-wamr-ios.sh
//
// Common architecture (both backends):
//   WASM Runtime (wazero or WAMR)
//     -> TinyEMU-c2w (MIT)  — RISC-V64 CPU emulator compiled to Wasm
//          -> Linux 6.1 kernel
//               -> Alpine 3.21 userspace (python3, pip, git, curl, wget, jq, bash, file)

#if C2WNET_AVAILABLE
import C2WNet
#endif

// MARK: - Persistent VM session (keeps TinyEMU alive between exec calls)
//
// Architecture:
//   First sandbox_exec boots TinyEMU (15-60s cold start).
//   Subsequent calls write commands directly to stdin and read stdout —
//   the kernel boot penalty is paid only once per app lifecycle.
//
// Protocol:
//   Boot marker: we write `echo "__WAMR_READY__"\n` to stdin before the VM
//   is even running; it gets buffered in the pipe and executed once ash starts.
//   We wait for `__WAMR_READY__` in stdout to confirm the VM is ready.
//
//   Per command: write `cd <dir>; <cmd>; echo "__WAMR_EXIT__$?"\n`,
//   then read stdout until the exit sentinel is found.
//   The tty echo and prompt lines are stripped by the existing noise filter.
//
// Thread safety: only one command at a time (enforced by sessionLock).
private final class WasmVMSession {
    // Pipe write-end for feeding commands into the VM
    let stdinWrite:    Int32
    // Pipe read-ends for consuming VM output
    let stdoutRead:    Int32
    let stderrRead:    Int32
    // Internal write-ends kept open so the drain threads don't see EOF prematurely.
    // Set to -1 when managed by an external runtime (e.g. C2WNet/wazero).
    let stdoutWriteInternal: Int32
    let stderrWriteInternal: Int32
    // Internal read-end of stdin (owned by runtime).
    // Set to -1 when managed by an external runtime.
    let stdinReadInternal: Int32

    // Which backend is running this session.
    enum Backend { case wamr, wazero }
    let backend: Backend

    // Rolling stdout accumulator: may contain data from previous reads
    var stdoutBuf = ""

    // Flag set when `__WAMR_READY__` has been seen in stdout
    var isReady = false

    // Set to true by the background VM thread when the module exits.
    // For wazero, checked via C2wnetIsVMRunning().
    var vmExited = false

    init(backend: Backend,
         stdinFds: (Int32, Int32),
         stdoutFds: (Int32, Int32),
         stderrFds: (Int32, Int32)) {
        self.backend            = backend
        stdinReadInternal       = stdinFds.0
        stdinWrite              = stdinFds.1
        stdoutRead              = stdoutFds.0
        stdoutWriteInternal     = stdoutFds.1
        stderrRead              = stderrFds.0
        stderrWriteInternal     = stderrFds.1
    }

    var isVMExited: Bool {
        #if C2WNET_AVAILABLE
        if backend == .wazero {
            return !C2wnetIsVMRunning()
        }
        #endif
        return vmExited
    }

    // Tear down all resources. Call from the session lock.
    func teardown() {
        #if C2WNET_AVAILABLE
        if backend == .wazero {
            C2wnetStopVM()
            // Close only the Swift-owned fds (internal fds are -1 / managed by Go).
            for fd in [stdinWrite, stdoutRead, stderrRead] {
                if fd >= 0 { close(fd) }
            }
            return
        }
        #endif
        // WAMR backend: close all 6 fds.
        for fd in [stdinReadInternal, stdinWrite,
                   stdoutRead, stdoutWriteInternal,
                   stderrRead, stderrWriteInternal] {
            if fd >= 0 { close(fd) }
        }
    }
}

class WasmSandboxHandler: NSObject, FlutterStreamHandler {

    // URL and SHA256 of the pre-built Wasm artefact.
    // Generated by scripts/ios-sandbox/build.sh or the build-ios-sandbox CI workflow.
    // Update both when publishing a new image version via GitHub release.
    static let wasmDownloadURL = "https://github.com/flutterclaw/flutterclaw/releases/download/ios-sandbox%2Fv3.21.0-1/alpine-ios-sandbox.initialized.wasm"
    static let wasmSHA256 = ""  // Temporarily disabled for testing (actual: e99387410388ca2199e261a514f3eedb44cde2e61178c61b1de6719521a9568c)
    static let wasmVersion = "3.21.0-1"

    // wasm_runtime_init must be called exactly once per process lifetime (WAMR only).
    private static var runtimeInitialised = false

    // Persistent VM session — nil until first sandbox_exec.
    private var vmSession: WasmVMSession?
    private let sessionLock = NSLock()

    private let channel: FlutterMethodChannel

    // EventChannel for streaming output
    private var eventSink: FlutterEventSink?

    init(messenger: FlutterBinaryMessenger) {
        channel = FlutterMethodChannel(
            name: "ai.flutterclaw/sandbox",
            binaryMessenger: messenger
        )
        super.init()
        channel.setMethodCallHandler { [weak self] call, result in
            self?.handleMethodCall(call, result: result)
        }
    }

    // MARK: - FlutterStreamHandler

    func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
        eventSink = events
        print("[SandboxSwift] onListen called, args=\(String(describing: arguments))")
        // Command args are passed via receiveBroadcastStream(args) from Dart.
        // Start streaming execution now that the sink is guaranteed to be set.
        if let args = arguments as? [String: Any],
           let command = args["command"] as? String, !command.isEmpty {
            let timeoutMs = (args["timeout_ms"] as? Int) ?? 30_000
            let workingDir = (args["working_dir"] as? String) ?? "/root"

            let wasmFile = wasmFileURL()
            guard FileManager.default.fileExists(atPath: wasmFile.path) else {
                print("[SandboxSwift] wasm not provisioned, sending error exit")
                events(["type": "exit", "exit_code": -1, "timed_out": false, "error": "Sandbox not provisioned."])
                events(FlutterEndOfEventStream)
                return nil
            }

            print("[SandboxSwift] dispatching runInVMStreaming for: \(command)")
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                guard let self else { return }
                self.runInVMStreaming(
                    command: command,
                    workingDir: workingDir,
                    timeoutMs: timeoutMs
                )
            }
        } else {
            print("[SandboxSwift] onListen: no command in args")
        }
        return nil
    }

    func onCancel(withArguments arguments: Any?) -> FlutterError? {
        print("[SandboxSwift] onCancel called")
        eventSink = nil
        return nil
    }

    private func handleMethodCall(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "sandbox_status":
            handleStatus(result: result)
        case "sandbox_setup":
            handleSetup(result: result)
        case "sandbox_exec":
            handleExec(call: call, result: result)
        case "sandbox_kill":
            handleKill(result: result)
        case "sandbox_write_stdin":
            handleWriteStdin(call: call, result: result)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // MARK: - sandbox_status

    private func handleStatus(result: @escaping FlutterResult) {
        let wasmURL = wasmFileURL()
        let wasmReady = FileManager.default.fileExists(atPath: wasmURL.path)
        let sharedPath = sharedDirectoryURL().path
        let sessionActive = sessionLock.withLock { vmSession?.isReady == true }

        #if C2WNET_AVAILABLE
        let hasNetwork = true
        let runtimeName = "wazero"
        #elseif WAMR_AVAILABLE
        let hasNetwork = false
        let runtimeName = "wamr"
        #else
        let hasNetwork = false
        let runtimeName = "none"
        #endif

        let note: String
        if sessionActive {
            note = "Alpine 3.21 (riscv64). VM running — next exec is instant."
                + (hasNetwork ? " Network enabled." : "")
        } else if wasmReady {
            note = "Alpine 3.21 (riscv64 emulated, \(runtimeName))."
                + (hasNetwork
                    ? " Internet access enabled. apk add, curl, pip install work."
                    : " No internet in VM. Pre-installed: python3, pip, git, curl, wget, jq, bash, file.")
        } else {
            note = "Call sandbox_setup to download the Alpine Wasm image (~100-120 MB)."
        }

        result([
            "ready": wasmReady,
            "platform": "ios",
            "emulator": "tinyemu-riscv64",
            "runtime": runtimeName,
            "network": hasNetwork,
            "wasm_version": Self.wasmVersion,
            "shared_path": sharedPath,
            "root_path": rootPersistenceDirectoryURL().path,
            "proot_available": false,
            "rootfs_available": wasmReady,
            "vm_session_active": sessionActive,
            "note": note,
        ] as [String: Any])
    }

    // MARK: - sandbox_setup

    private func handleSetup(result: @escaping FlutterResult) {
        // Kill any live VM session before re-provisioning so the new Wasm file
        // is loaded on the next sandbox_exec call.
        sessionLock.withLock {
            vmSession?.teardown()
            vmSession = nil
        }
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            do {
                try self.provision()
                DispatchQueue.main.async {
                    result(["ready": true, "platform": "ios"])
                }
            } catch {
                DispatchQueue.main.async {
                    result(["error": true, "message": error.localizedDescription])
                }
            }
        }
    }

    // Idempotent: skips download if the Wasm file already exists with the
    // correct version marker. Creates the shared directory regardless.
    private func provision() throws {
        let fm = FileManager.default
        let sandboxDir = sandboxDirectoryURL()
        let sharedDir = sharedDirectoryURL()
        let wasmFile = wasmFileURL()
        let versionFile = sandboxDir.appendingPathComponent(".wasm_version")

        // Create sandbox, shared, and persistent root directories.
        try fm.createDirectory(at: sandboxDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: sharedDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: rootPersistenceDirectoryURL(), withIntermediateDirectories: true)

        // Check if existing Wasm matches current version.
        if fm.fileExists(atPath: wasmFile.path),
           let storedVersion = try? String(contentsOf: versionFile, encoding: .utf8),
           storedVersion.trimmingCharacters(in: .whitespacesAndNewlines) == Self.wasmVersion {
            return  // Already provisioned and up to date.
        }

        // Remove stale Wasm if present.
        if fm.fileExists(atPath: wasmFile.path) {
            try fm.removeItem(at: wasmFile)
        }

        // Download the Wasm artefact.
        guard let url = URL(string: Self.wasmDownloadURL) else {
            throw SandboxError.invalidURL
        }

        var downloadError: Error?
        var downloadedURL: URL?
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.downloadTask(with: url) { tmpURL, response, error in
            defer { semaphore.signal() }
            if let error {
                downloadError = error
                return
            }
            guard let tmpURL,
                  let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                downloadError = SandboxError.downloadFailed(
                    (response as? HTTPURLResponse)?.statusCode ?? 0
                )
                return
            }
            downloadedURL = tmpURL
        }
        task.resume()
        semaphore.wait()

        if let error = downloadError { throw error }
        guard let src = downloadedURL else { throw SandboxError.downloadFailed(0) }

        try fm.moveItem(at: src, to: wasmFile)

        // Verify SHA256 if configured (skip when empty for dev convenience).
        if !Self.wasmSHA256.isEmpty {
            let data = try Data(contentsOf: wasmFile)
            let digest = sha256Hex(data)
            guard digest == Self.wasmSHA256 else {
                try? fm.removeItem(at: wasmFile)
                throw SandboxError.sha256Mismatch(expected: Self.wasmSHA256, got: digest)
            }
        }

        try Self.wasmVersion.write(to: versionFile, atomically: true, encoding: .utf8)
    }

    // MARK: - sandbox_exec

    private func handleExec(call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any],
              let command = args["command"] as? String, !command.isEmpty else {
            result(["error": true, "message": "command is required"])
            return
        }
        let timeoutMs = (args["timeout_ms"] as? Int) ?? 30_000
        let workingDir = (args["working_dir"] as? String) ?? "/root"

        let wasmFile = wasmFileURL()
        guard FileManager.default.fileExists(atPath: wasmFile.path) else {
            result(["error": true, "message": "Sandbox not provisioned. Call sandbox_setup first."])
            return
        }

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            let execResult = self.runInVM(
                command: command,
                workingDir: workingDir,
                timeoutMs: timeoutMs
            )
            DispatchQueue.main.async { result(execResult) }
        }
    }

    #if C2WNET_AVAILABLE || WAMR_AVAILABLE
    private func runInVMStreaming(command: String, workingDir: String, timeoutMs: Int) {
        print("[SandboxSwift] runInVMStreaming start: \(command)")
        let sink = eventSink

        sessionLock.lock()
        if let s = vmSession, s.isVMExited {
            print("[SandboxSwift] previous session exited, tearing down")
            s.teardown()
            vmSession = nil
        }
        if vmSession == nil {
            print("[SandboxSwift] creating new VM session")
            let bootResult = createSession()
            if let err = bootResult.error {
                print("[SandboxSwift] createSession error: \(err)")
                sessionLock.unlock()
                DispatchQueue.main.async {
                    sink?(["type": "exit", "exit_code": -1, "timed_out": false, "error": err])
                    sink?(FlutterEndOfEventStream)
                }
                return
            }
            print("[SandboxSwift] session created OK")
        }
        let session = vmSession!
        sessionLock.unlock()

        // Wait for ready
        let bootDeadline = DispatchTime.now() + .seconds(120)
        if !session.isReady {
            print("[SandboxSwift] waiting for VM boot sentinel...")
            if !waitForSentinel(session: session, sentinel: "__WAMR_READY__", deadline: bootDeadline) {
                print("[SandboxSwift] VM boot timed out")
                sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
                DispatchQueue.main.async {
                    sink?(["type": "exit", "exit_code": -1, "timed_out": true, "error": "VM boot timed out"])
                    sink?(FlutterEndOfEventStream)
                }
                return
            }
            print("[SandboxSwift] VM ready")
            session.isReady = true
        } else {
            print("[SandboxSwift] VM already ready, skipping boot wait")
        }

        // Run the command
        let sentinel = "__WAMR_EXIT__"
        let wrappedCmd =
            "cd \(shellEscape(workingDir)) 2>/dev/null || cd /root\n" +
            command + "\n" +
            "echo \"\(sentinel)$?\"\n"
        let cmdData = (wrappedCmd + "\n").data(using: .utf8)!
        cmdData.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, cmdData.count)
        }

        // Poll stdout with streaming output
        let deadline = DispatchTime.now() + .milliseconds(timeoutMs)
        var chunk = [UInt8](repeating: 0, count: 8192)
        var lastEmittedLen = session.stdoutBuf.count
        var chunkCount = 0
        print("[SandboxSwift] starting poll loop, buf=\(lastEmittedLen), sink=\(sink != nil ? "ok" : "nil")")

        while DispatchTime.now() < deadline {
            let n = read(session.stdoutRead, &chunk, chunk.count)
            if n > 0 {
                session.stdoutBuf += String(bytes: chunk[..<n], encoding: .utf8) ?? ""
                chunkCount += 1

                // Emit new data delta — raw, no noise stripping.
                // stripTinyEMUNoise() is stateful per-call and breaks on partial
                // chunks (output lines arrive separately from the prompt line),
                // causing it to discard all content. xterm renders raw VT100 fine.
                let currentLen = session.stdoutBuf.count
                if currentLen > lastEmittedLen {
                    let startIdx = session.stdoutBuf.index(session.stdoutBuf.startIndex, offsetBy: lastEmittedLen)
                    let delta = String(session.stdoutBuf[startIdx...])
                    if !delta.isEmpty {
                        print("[SandboxSwift] emitting stdout chunk #\(chunkCount) len=\(delta.count)")
                        DispatchQueue.main.async {
                            sink?(["type": "stdout", "data": delta])
                        }
                    }
                    lastEmittedLen = currentLen
                }

                if session.stdoutBuf.contains(sentinel) { break }
            } else if n == 0 {
                // EOF — write-end of pipe closed (VM exited)
                print("[SandboxSwift] read returned EOF (pipe closed)")
                break
            } else {
                // EAGAIN (O_NONBLOCK) or error — sleep 20ms and retry
                usleep(20_000)
            }
            if session.isVMExited {
                print("[SandboxSwift] VM exited flag set, breaking poll")
                break
            }
        }

        let timedOut = !session.stdoutBuf.contains(sentinel)
        print("[SandboxSwift] poll done: timedOut=\(timedOut), chunks=\(chunkCount), sentinel=\(!timedOut)")
        if timedOut {
            print("[SandboxSwift] command timed out, attempting graceful recovery...")
            let recovered = attemptGracefulRecovery(session: session, timeoutSeconds: 10)
            if !recovered {
                sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
            }
            DispatchQueue.main.async {
                sink?(["type": "exit", "exit_code": -1, "timed_out": true])
                sink?(FlutterEndOfEventStream)
            }
            return
        }

        // Extract exit code from sentinel
        let raw = session.stdoutBuf
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")
        guard let range = raw.range(of: sentinel) else {
            DispatchQueue.main.async {
                sink?(["type": "exit", "exit_code": 0, "timed_out": false])
                sink?(FlutterEndOfEventStream)
            }
            return
        }

        let afterSentinel = String(raw[range.upperBound...])
        let firstLine = afterSentinel.components(separatedBy: "\n").first ?? ""
        let exitCode = Int(firstLine.trimmingCharacters(in: .whitespacesAndNewlines)) ?? 0

        let remaining: String
        if let nl = afterSentinel.firstIndex(of: "\n") {
            remaining = String(afterSentinel[afterSentinel.index(after: nl)...])
        } else {
            remaining = ""
        }
        session.stdoutBuf = remaining

        print("[SandboxSwift] exit code=\(exitCode), sending exit+EndOfEventStream")
        DispatchQueue.main.async {
            sink?(["type": "exit", "exit_code": exitCode, "timed_out": false])
            sink?(FlutterEndOfEventStream)
        }
    }
    #else
    private func runInVMStreaming(command: String, workingDir: String, timeoutMs: Int) {
        let sink = eventSink
        DispatchQueue.main.async {
            sink?(["type": "exit", "exit_code": -1, "error": "No WASM runtime available."])
            sink?(FlutterEndOfEventStream)
        }
    }
    #endif

    // MARK: - sandbox_kill

    private func handleKill(result: @escaping FlutterResult) {
        sessionLock.lock()
        guard let session = vmSession, session.isReady else {
            // No active session — nothing to kill.
            vmSession?.teardown()
            vmSession = nil
            sessionLock.unlock()
            result(["killed": true, "method": "none"])
            return
        }
        sessionLock.unlock()

        // Stage 1: Send Ctrl+C (SIGINT) to interrupt the running process.
        let ctrlC = Data([0x03])
        ctrlC.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, ctrlC.count)
        }

        // Stage 2: Try graceful recovery on a background thread.
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            usleep(500_000)  // 500ms grace period for Ctrl+C to propagate

            let recovered = self.attemptGracefulRecovery(session: session, timeoutSeconds: 3)
            if recovered {
                DispatchQueue.main.async {
                    result(["killed": true, "method": "sigint", "session_preserved": true])
                }
            } else {
                // Stage 3: Full teardown — VM is unresponsive.
                self.sessionLock.withLock {
                    self.vmSession?.teardown()
                    self.vmSession = nil
                }
                DispatchQueue.main.async {
                    result(["killed": true, "method": "teardown", "session_preserved": false])
                }
            }
        }
    }

    // MARK: - sandbox_write_stdin

    private func handleWriteStdin(call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any],
              let data = args["data"] as? String, !data.isEmpty else {
            result(["error": true, "message": "data is required"])
            return
        }

        sessionLock.lock()
        guard let session = vmSession, session.isReady else {
            sessionLock.unlock()
            result(["error": true, "message": "No active VM session"])
            return
        }
        sessionLock.unlock()

        guard let bytes = data.data(using: .utf8) else {
            result(["error": true, "message": "Failed to encode data as UTF-8"])
            return
        }

        bytes.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, bytes.count)
        }
        result(["written": bytes.count])
    }

    // Runs a shell command inside TinyEMU.
    private func runInVM(command: String, workingDir: String, timeoutMs: Int) -> [String: Any] {
        let maxOutputBytes = 65_536

        #if C2WNET_AVAILABLE
        return execPersistent(command: command,
                              workingDir: workingDir,
                              timeoutMs: timeoutMs,
                              maxOutputBytes: maxOutputBytes)
        #elseif WAMR_AVAILABLE
        return execPersistent(command: command,
                              workingDir: workingDir,
                              timeoutMs: timeoutMs,
                              maxOutputBytes: maxOutputBytes)
        #else
        return [
            "error": true,
            "message": "No WASM runtime available. Run scripts/build-c2wnet-ios.sh (or scripts/build-wamr-ios.sh) then pod install.",
        ]
        #endif
    }

    #if C2WNET_AVAILABLE || WAMR_AVAILABLE

    // MARK: - Persistent VM execution (shared between backends)

    /// Main entry point for persistent execution. Creates a session on first
    /// call (cold boot), then reuses it for subsequent commands.
    private func execPersistent(command: String,
                                workingDir: String,
                                timeoutMs: Int,
                                maxOutputBytes: Int) -> [String: Any] {
        sessionLock.lock()
        // Teardown dead sessions (VM exited unexpectedly).
        if let s = vmSession, s.isVMExited {
            s.teardown()
            vmSession = nil
        }

        if vmSession == nil {
            // Cold boot: create pipes, load module, start VM background thread.
            let bootResult = createSession()
            if let err = bootResult.error {
                sessionLock.unlock()
                return ["error": true, "message": err]
            }
        }
        let session = vmSession!
        sessionLock.unlock()

        // Wait for ready (blocks until kernel boot on first call, instant after).
        let bootDeadline = DispatchTime.now() + .seconds(120)
        if !session.isReady {
            if !waitForSentinel(session: session,
                                sentinel: "__WAMR_READY__",
                                deadline: bootDeadline) {
                sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
                return ["error": true, "message": "VM boot timed out (>120s)."]
            }
            session.isReady = true
        }

        // Run the command.
        let sentinel = "__WAMR_EXIT__"
        let wrappedCmd =
            "cd \(shellEscape(workingDir)) 2>/dev/null || cd /root\n" +
            command + "\n" +
            "echo \"\(sentinel)$?\"\n"
        let cmdData = (wrappedCmd + "\n").data(using: .utf8)!
        cmdData.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, cmdData.count)
        }

        let deadline = DispatchTime.now() + .milliseconds(timeoutMs)
        if !waitForSentinel(session: session, sentinel: sentinel, deadline: deadline) {
            // Timed out — try graceful recovery before destroying the VM.
            let recovered = attemptGracefulRecovery(session: session, timeoutSeconds: 10)
            if !recovered {
                sessionLock.withLock { vmSession?.teardown(); vmSession = nil }
            }
            return ["exit_code": -1, "stdout": "", "stderr": "Command timed out.", "timed_out": true]
        }

        // Extract output up to and including the sentinel from the buffer.
        let raw = session.stdoutBuf
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")

        // Find sentinel position and split buffer: keep output before sentinel,
        // leave any trailing data in the buffer for the next command.
        guard let range = raw.range(of: sentinel) else {
            return ["exit_code": 0, "stdout": stripTinyEMUNoise(raw), "timed_out": false]
        }

        var outputPart = String(raw[..<range.lowerBound])
        let afterSentinel = String(raw[range.upperBound...])

        // Extract exit code from the line immediately following the sentinel.
        let firstLine = afterSentinel.components(separatedBy: "\n").first ?? ""
        let exitCodeStr = firstLine.trimmingCharacters(in: .whitespacesAndNewlines)
        let exitCode = Int(exitCodeStr) ?? 0

        // Retain anything after the exit code digit(s) + newline for next command.
        let remaining: String
        if let nl = afterSentinel.firstIndex(of: "\n") {
            remaining = String(afterSentinel[afterSentinel.index(after: nl)...])
        } else {
            remaining = ""
        }
        session.stdoutBuf = remaining

        outputPart = stripTinyEMUNoise(outputPart)
        return [
            "exit_code": exitCode,
            "stdout": outputPart,
            "stderr": "",
            "timed_out": false,
        ]
    }

    // -----------------------------------------------------------------------
    // Session creation
    // -----------------------------------------------------------------------

    private struct CreateSessionResult {
        let error: String?
    }

    private func createSession() -> CreateSessionResult {
        #if C2WNET_AVAILABLE
        return createWazeroSession()
        #elseif WAMR_AVAILABLE
        return createWAMRSession()
        #else
        return CreateSessionResult(error: "No WASM runtime available.")
        #endif
    }

    #if C2WNET_AVAILABLE
    // -- wazero session (via C2WNet gomobile bridge) --

    private func createWazeroSession() -> CreateSessionResult {
        let wasmPath = wasmFileURL().path
        let rootPath = rootPersistenceDirectoryURL().path
        let sharedPath = sharedDirectoryURL().path

        // Start the wazero VM + gvisor-tap-vsock networking.
        // Go creates internal pipes; we get fd numbers from getter functions.
        var err: NSError?
        C2wnetStartVM(wasmPath, rootPath, sharedPath, &err)
        if let err = err {
            return CreateSessionResult(error: "C2WNet: \(err.localizedDescription)")
        }

        let stdinWrite = C2wnetStdinWriteFD()
        let stdoutRead = C2wnetStdoutReadFD()
        let stderrRead = C2wnetStderrReadFD()

        guard stdinWrite >= 0, stdoutRead >= 0, stderrRead >= 0 else {
            C2wnetStopVM()
            return CreateSessionResult(error: "C2WNet: invalid pipe fds")
        }

        // Set stdout/stderr read-ends to O_NONBLOCK so the poll loops in
        // waitForSentinel and runInVMStreaming can check the deadline between
        // read() calls instead of blocking indefinitely.
        let flags = fcntl(stdoutRead, F_GETFL, 0)
        fcntl(stdoutRead, F_SETFL, flags | O_NONBLOCK)
        let errFlags = fcntl(stderrRead, F_GETFL, 0)
        fcntl(stderrRead, F_SETFL, errFlags | O_NONBLOCK)

        // Write ready probe immediately — buffered in pipe until shell starts.
        // DNS: use the gvisor-tap-vsock gateway (192.168.127.1) which provides a
        // DNS proxy. The image already ships with this, but DHCP or init scripts
        // may overwrite it, so we set it explicitly.
        //
        // Network wait: the gvisor-tap-vsock bridge goroutine connects to the
        // WASI TCP listener AFTER boot. DHCP then assigns 192.168.127.3 to eth0.
        // We must wait for eth0 to get an IP before signaling READY, otherwise
        // commands like `apk add` fail with "network unreachable".
        // Fallback: if DHCP doesn't work within 20s, manually configure the
        // static IP + default route so networking still works.
        let probe = """
            echo "nameserver 192.168.127.1" > /etc/resolv.conf
            i=0; while [ $i -lt 20 ]; do ifconfig eth0 2>/dev/null | grep -q 'inet ' && break; i=$((i+1)); sleep 1; done
            ifconfig eth0 2>/dev/null | grep -q 'inet ' || { ifconfig eth0 192.168.127.3 netmask 255.255.255.0 up 2>/dev/null; route add default gw 192.168.127.1 2>/dev/null; }
            echo "__WAMR_READY__"

            """
        let probeData = probe.data(using: .utf8)!
        probeData.withUnsafeBytes { ptr in
            _ = write(stdinWrite, ptr.baseAddress!, probeData.count)
        }

        let session = WasmVMSession(
            backend: .wazero,
            stdinFds:  (-1, stdinWrite),    // Go owns read-end
            stdoutFds: (stdoutRead, -1),    // Go owns write-end
            stderrFds: (stderrRead, -1)     // Go owns write-end
        )
        vmSession = session
        return CreateSessionResult(error: nil)
    }
    #endif

    #if WAMR_AVAILABLE
    // -- WAMR session (C API via bridging header) --

    private func createWAMRSession() -> CreateSessionResult {
        guard let wasmBytes = try? Data(contentsOf: wasmFileURL()) else {
            return CreateSessionResult(error: "Failed to read Wasm file.")
        }

        let rootPath   = rootPersistenceDirectoryURL().path
        let sharedPath = sharedDirectoryURL().path
        let argv: [String] = ["/bin/sh"]
        let dirs: [String] = [rootPath, sharedPath]
        let envs: [String] = ["TERM=xterm-256color", "HOME=/root",
                               "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]

        var inPipe  = [Int32](repeating: 0, count: 2)
        var outPipe = [Int32](repeating: 0, count: 2)
        var errPipe = [Int32](repeating: 0, count: 2)
        pipe(&inPipe); pipe(&outPipe); pipe(&errPipe)

        // Set stdout read-end non-blocking so waitForSentinel can poll.
        let flags = fcntl(outPipe[0], F_GETFL, 0)
        fcntl(outPipe[0], F_SETFL, flags | O_NONBLOCK)

        // Write ready probe immediately — buffered in pipe until shell starts.
        // WAMR has no networking, but set DNS for consistency.
        let probe = """
            echo "__WAMR_READY__"

            """
        let probeData = probe.data(using: .utf8)!
        probeData.withUnsafeBytes { ptr in
            _ = write(inPipe[1], ptr.baseAddress!, probeData.count)
        }

        let session = WasmVMSession(
            backend: .wamr,
            stdinFds:  (inPipe[0],  inPipe[1]),
            stdoutFds: (outPipe[0], outPipe[1]),
            stderrFds: (errPipe[0], errPipe[1])
        )
        vmSession = session

        // Load + instantiate WAMR (done once per session).
        var loadError = ""
        var mutableWasm = wasmBytes
        mutableWasm.withUnsafeMutableBytes { (rawPtr: UnsafeMutableRawBufferPointer) in
            guard let base = rawPtr.baseAddress else { loadError = "Nil Wasm buffer"; return }

            if !Self.runtimeInitialised {
                _ = wasm_runtime_init()
                Self.runtimeInitialised = true
            }

            var errBuf = [CChar](repeating: 0, count: 256)
            guard let module = wasm_runtime_load(
                base.assumingMemoryBound(to: UInt8.self),
                UInt32(wasmBytes.count),
                &errBuf, UInt32(errBuf.count)
            ) else {
                loadError = String(cString: errBuf)
                return
            }

            var cArgv = argv.map { strdup($0) }
            var cDirs = dirs.map { strdup($0) }
            var cEnvs = envs.map { strdup($0) }
            defer {
                cArgv.forEach { free($0) }
                cDirs.forEach { free($0) }
                cEnvs.forEach { free($0) }
            }

            var constDirs = cDirs.map { UnsafePointer($0) }
            var constEnvs = cEnvs.map { UnsafePointer($0) }
            cArgv.withUnsafeMutableBufferPointer { ab in
            constDirs.withUnsafeMutableBufferPointer { db in
            constEnvs.withUnsafeMutableBufferPointer { eb in
                wasm_runtime_set_wasi_args_ex(
                    module,
                    db.baseAddress, UInt32(dirs.count),
                    nil, 0,
                    eb.baseAddress, UInt32(envs.count),
                    ab.baseAddress, Int32(argv.count),
                    Int64(inPipe[0]),   // stdin  read-end
                    Int64(outPipe[1]),  // stdout write-end
                    Int64(errPipe[1])   // stderr write-end
                )
            }}}

            guard let instance = wasm_runtime_instantiate(
                module,
                1024 * 1024,
                16 * 1024 * 1024,
                &errBuf, UInt32(errBuf.count)
            ) else {
                wasm_runtime_unload(module)
                loadError = String(cString: errBuf)
                return
            }

            // Run the VM on a permanent background thread.
            let capturedArgv = argv
            DispatchQueue.global(qos: .userInitiated).async { [weak session] in
                _ = wasm_runtime_init_thread_env()
                defer { wasm_runtime_destroy_thread_env() }

                var threadArgv = capturedArgv.map { strdup($0) }
                defer { threadArgv.forEach { free($0) } }
                threadArgv.withUnsafeMutableBufferPointer { buf in
                    _ = wasm_application_execute_main(instance, Int32(capturedArgv.count), buf.baseAddress)
                }
                wasm_runtime_deinstantiate(instance)
                wasm_runtime_unload(module)
                session?.vmExited = true
            }
        }

        if !loadError.isEmpty {
            session.teardown()
            vmSession = nil
            return CreateSessionResult(error: "WAMR load error: \(loadError)")
        }
        return CreateSessionResult(error: nil)
    }
    #endif

    // -----------------------------------------------------------------------
    // Sentinel-based stdout polling (non-blocking reads with timeout)
    // -----------------------------------------------------------------------

    /// Reads from session.stdoutRead (non-blocking) until `sentinel` appears
    /// in the accumulated buffer, or `deadline` is reached.
    /// Returns true if sentinel was found.
    private func waitForSentinel(session: WasmVMSession,
                                  sentinel: String,
                                  deadline: DispatchTime) -> Bool {
        var chunk = [UInt8](repeating: 0, count: 8192)
        while DispatchTime.now() < deadline {
            let n = read(session.stdoutRead, &chunk, chunk.count)
            if n > 0 {
                session.stdoutBuf += String(bytes: chunk[..<n], encoding: .utf8) ?? ""
                if session.stdoutBuf.contains(sentinel) { return true }
            } else {
                // EAGAIN — no data yet; sleep 20ms before next poll.
                usleep(20_000)
            }
            if session.isVMExited { return false }
        }
        return false
    }

    // -----------------------------------------------------------------------
    // Graceful recovery after timeout or kill (Ctrl+C + re-sync)
    // -----------------------------------------------------------------------

    /// Attempts to recover the VM session after a command timeout or kill.
    /// Sends Ctrl+C to interrupt the running process, drains residual output,
    /// then sends a recovery sentinel probe and waits for it.
    /// Returns true if the shell responded (session is reusable), false if
    /// the VM is unresponsive (caller should teardown).
    private func attemptGracefulRecovery(session: WasmVMSession,
                                          timeoutSeconds: Int = 10) -> Bool {
        print("[SandboxSwift] attemptGracefulRecovery: sending Ctrl+C")
        // 1. Send Ctrl+C (ASCII ETX) to interrupt whatever is running.
        let ctrlC = Data([0x03])
        ctrlC.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, ctrlC.count)
        }

        // 2. Wait for the signal to propagate through TinyEMU emulation.
        usleep(300_000)  // 300ms

        // 3. Drain any buffered output (post-interrupt noise).
        var drainBuf = [UInt8](repeating: 0, count: 4096)
        while true {
            let n = read(session.stdoutRead, &drainBuf, drainBuf.count)
            if n <= 0 { break }  // EAGAIN or EOF
        }

        // 4. Clear the rolling buffer so the sentinel search starts clean.
        session.stdoutBuf = ""

        // 5. Send a recovery sentinel probe.
        let recoverySentinel = "__WAMR_RECOVERY__"
        let probe = "\necho \"\(recoverySentinel)\"\n"
        let probeData = probe.data(using: .utf8)!
        probeData.withUnsafeBytes { ptr in
            _ = write(session.stdinWrite, ptr.baseAddress!, probeData.count)
        }

        // 6. Wait for the recovery sentinel.
        let deadline = DispatchTime.now() + .seconds(timeoutSeconds)
        let found = waitForSentinel(session: session,
                                     sentinel: recoverySentinel,
                                     deadline: deadline)
        if found {
            // Clean the buffer of recovery sentinel remnants.
            session.stdoutBuf = ""
            print("[SandboxSwift] recovery succeeded, session preserved")
        } else {
            print("[SandboxSwift] recovery failed, VM unresponsive")
        }
        return found
    }

    #endif  // C2WNET_AVAILABLE || WAMR_AVAILABLE

    private func shellEscape(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Paths

    func wasmFileURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("alpine-ios-sandbox.wasm")
    }

    func sharedDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("shared")
    }

    // Persistent /root/ for the Alpine guest.
    // Mounted via --dir / FSConfig + container2wasm virtio-9p at the same absolute path
    // inside the VM, so files written to /root/ inside Alpine survive across calls.
    func rootPersistenceDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("root")
    }

    func sandboxDirectoryURL() -> URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("sandbox")
    }
}

// MARK: - TinyEMU output post-processing

// Strip the UART echo preamble and ash shell-prompt lines from TinyEMU stdout.
//
// Raw TinyEMU stdout structure (serial console / tty echo):
//
//   [preamble] echo of all stdin chars (before shell is ready)
//   ~ # cmd1          <- ash prompt + command
//   output1           <- kept
//   /tmp # cmd2       <- ash prompt (workdir changed)
//   output2           <- kept
//   ...
//
// Prompt lines are identified by: starts with "~" or "/" and contains " # "
// with no space in the working-directory portion (e.g. "~ # " or "/tmp # ").
//
// Limitation: output lines that happen to match the prompt pattern (e.g. a
// line like "/bin # something") will be incorrectly stripped.  This is
// acceptable for typical command output.
private func stripTinyEMUNoise(_ raw: String) -> String {
    let lines = raw.components(separatedBy: "\n")
    var pastPreamble = false
    var result: [String] = []

    for line in lines {
        if isTinyEMUPromptLine(line) {
            pastPreamble = true
            // Skip prompt lines.
        } else if pastPreamble {
            result.append(line)
        }
        // Skip preamble lines (before first prompt).
    }
    return result.joined(separator: "\n")
}

// Returns true if `line` looks like an ash prompt: starts with "~" or "/"
// and contains " # " with no spaces before the " # ".
private func isTinyEMUPromptLine(_ line: String) -> Bool {
    guard line.hasPrefix("~") || line.hasPrefix("/") else { return false }
    guard let hashRange = line.range(of: " # ") else { return false }
    let workingDir = String(line[..<hashRange.lowerBound])
    return !workingDir.contains(" ")
}

// MARK: - SHA256

import CommonCrypto

private func sha256Hex(_ data: Data) -> String {
    var digest = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
    data.withUnsafeBytes { CC_SHA256($0.baseAddress, CC_LONG(data.count), &digest) }
    return digest.map { String(format: "%02x", $0) }.joined()
}

// MARK: - Helpers

// Drain a pipe read-fd into a Data buffer, capped at `max` bytes.
// Reads until EOF (write end closed) or cap reached. Closes the fd when done.
private func wasmDrainPipe(_ fd: Int32, max: Int) -> Data {
    var data = Data()
    var buf  = [UInt8](repeating: 0, count: 4096)
    while data.count < max {
        let n = read(fd, &buf, min(buf.count, max - data.count))
        if n <= 0 { break }
        data.append(contentsOf: buf[..<n])
    }
    close(fd)
    return data
}

// MARK: - NSLock compatibility (withLock added in Swift 5.7 / iOS 16)

private extension NSLock {
    @discardableResult
    func withLock<T>(_ body: () throws -> T) rethrows -> T {
        lock()
        defer { unlock() }
        return try body()
    }
}

// MARK: - Errors

private enum SandboxError: LocalizedError {
    case invalidURL
    case downloadFailed(Int)
    case sha256Mismatch(expected: String, got: String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid Wasm download URL."
        case .downloadFailed(let code):
            return "Failed to download Alpine Wasm image (HTTP \(code))."
        case .sha256Mismatch(let expected, let got):
            return "Wasm image SHA256 mismatch. Expected \(expected), got \(got)."
        }
    }
}
