import Flutter
import Foundation
import Darwin  // pipe, read, write, close

// WasmSandboxHandler — iOS implementation of the ai.flutterclaw/sandbox MethodChannel.
//
// Architecture:
//   WAMR interpreter (Apache 2.0)
//     └─ TinyEMU-c2w (MIT)  — RISC-V64 CPU emulator compiled to Wasm
//          └─ Linux 6.1 kernel (custom, CONFIG_RISCV_SBI_V01=y)
//               └─ Alpine 3.21 userspace (python3, pip, git, curl, wget, jq, bash, file)
//
// Limitations vs Android:
//   - No internet in guest VM (WAMR networking WIP) → apk add online fails
//   - Packages fixed at image build time (pre-installed: python3, pip, git, curl, wget, jq, bash, file)
//   - ~10–100× slower than Android (RISC-V emulation on ARM64 hardware)
//   - riscv64 architecture (`uname -m` → riscv64)
//   - Single-core CPU (no SMP)
//
// WAMR integration:
//   WAMR is integrated via its C API through a bridging header (Runner-Bridging-Header.h).
//   The xcframework lives at ios/WAMR/wamr.xcframework.
//   sandbox_exec calls wasm_runtime_init(), loads the Wasm module, sets --dir for file
//   sharing, and communicates with TinyEMU via the virtio serial console (stdin/stdout
//   of the Wasm instance).

class WasmSandboxHandler {

    // URL and SHA256 of the pre-built Wasm artefact.
    // Generated by scripts/ios-sandbox/build.sh or the build-ios-sandbox CI workflow.
    // Update both when publishing a new image version via GitHub release.
    static let wasmDownloadURL = "https://github.com/flutterclaw/flutterclaw/releases/download/ios-sandbox%2Fv3.21.0-1/alpine-ios-sandbox.initialized.wasm"
    static let wasmSHA256 = "8bf66d9b7702ae97bd60f97637b305ca1791a77168fe851b1af8bc2e28bb2ff8"
    static let wasmVersion = "3.21.0-1"

    // wasm_runtime_init must be called exactly once per process lifetime.
    private static var runtimeInitialised = false

    private let channel: FlutterMethodChannel

    init(messenger: FlutterBinaryMessenger) {
        channel = FlutterMethodChannel(
            name: "ai.flutterclaw/sandbox",
            binaryMessenger: messenger
        )
        channel.setMethodCallHandler { [weak self] call, result in
            self?.handleMethodCall(call, result: result)
        }
    }

    private func handleMethodCall(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "sandbox_status":
            handleStatus(result: result)
        case "sandbox_setup":
            handleSetup(result: result)
        case "sandbox_exec":
            handleExec(call: call, result: result)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // MARK: - sandbox_status

    private func handleStatus(result: @escaping FlutterResult) {
        let wasmURL = wasmFileURL()
        let wasmReady = FileManager.default.fileExists(atPath: wasmURL.path)
        let sharedPath = sharedDirectoryURL().path

        result([
            "ready": wasmReady,
            "platform": "ios",
            "emulator": "tinyemu-riscv64",
            "network": false,
            "wasm_version": Self.wasmVersion,
            "shared_path": sharedPath,
            "root_path": rootPersistenceDirectoryURL().path,
            "proot_available": false,
            "rootfs_available": wasmReady,
            "note": wasmReady
                ? "Alpine 3.21 (riscv64 emulated). No internet in VM. Pre-installed: python3, pip, git, curl, wget, jq, bash, file."
                : "Call sandbox_setup to download the Alpine Wasm image (~100-120 MB).",
        ] as [String: Any])
    }

    // MARK: - sandbox_setup

    private func handleSetup(result: @escaping FlutterResult) {
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            do {
                try self.provision()
                DispatchQueue.main.async {
                    result(["ready": true, "platform": "ios"])
                }
            } catch {
                DispatchQueue.main.async {
                    result(["error": true, "message": error.localizedDescription])
                }
            }
        }
    }

    // Idempotent: skips download if the Wasm file already exists with the
    // correct version marker. Creates the shared directory regardless.
    private func provision() throws {
        let fm = FileManager.default
        let sandboxDir = sandboxDirectoryURL()
        let sharedDir = sharedDirectoryURL()
        let wasmFile = wasmFileURL()
        let versionFile = sandboxDir.appendingPathComponent(".wasm_version")

        // Create sandbox, shared, and persistent root directories.
        try fm.createDirectory(at: sandboxDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: sharedDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: rootPersistenceDirectoryURL(), withIntermediateDirectories: true)

        // Check if existing Wasm matches current version.
        if fm.fileExists(atPath: wasmFile.path),
           let storedVersion = try? String(contentsOf: versionFile, encoding: .utf8),
           storedVersion.trimmingCharacters(in: .whitespacesAndNewlines) == Self.wasmVersion {
            return  // Already provisioned and up to date.
        }

        // Remove stale Wasm if present.
        if fm.fileExists(atPath: wasmFile.path) {
            try fm.removeItem(at: wasmFile)
        }

        // Download the Wasm artefact.
        guard let url = URL(string: Self.wasmDownloadURL) else {
            throw SandboxError.invalidURL
        }

        var downloadError: Error?
        var downloadedURL: URL?
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.downloadTask(with: url) { tmpURL, response, error in
            defer { semaphore.signal() }
            if let error {
                downloadError = error
                return
            }
            guard let tmpURL,
                  let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                downloadError = SandboxError.downloadFailed(
                    (response as? HTTPURLResponse)?.statusCode ?? 0
                )
                return
            }
            downloadedURL = tmpURL
        }
        task.resume()
        semaphore.wait()

        if let error = downloadError { throw error }
        guard let src = downloadedURL else { throw SandboxError.downloadFailed(0) }

        try fm.moveItem(at: src, to: wasmFile)

        // Verify SHA256 if configured (skip when empty for dev convenience).
        if !Self.wasmSHA256.isEmpty {
            let data = try Data(contentsOf: wasmFile)
            let digest = sha256Hex(data)
            guard digest == Self.wasmSHA256 else {
                try? fm.removeItem(at: wasmFile)
                throw SandboxError.sha256Mismatch(expected: Self.wasmSHA256, got: digest)
            }
        }

        try Self.wasmVersion.write(to: versionFile, atomically: true, encoding: .utf8)
    }

    // MARK: - sandbox_exec

    private func handleExec(call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any],
              let command = args["command"] as? String, !command.isEmpty else {
            result(["error": true, "message": "command is required"])
            return
        }
        let timeoutMs = (args["timeout_ms"] as? Int) ?? 30_000
        let workingDir = (args["working_dir"] as? String) ?? "/root"

        let wasmFile = wasmFileURL()
        guard FileManager.default.fileExists(atPath: wasmFile.path) else {
            result(["error": true, "message": "Sandbox not provisioned. Call sandbox_setup first."])
            return
        }

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            let execResult = self.runInVM(
                command: command,
                workingDir: workingDir,
                timeoutMs: timeoutMs
            )
            DispatchQueue.main.async { result(execResult) }
        }
    }

    // Runs a shell command inside TinyEMU via WAMR.
    //
    // Persistence:
    //   The guest's /root/ is mapped to <documents>/sandbox/root/ via WAMR --dir
    //   + container2wasm's virtio-9p bind-mount mechanism. Files written to /root/
    //   inside the VM are visible on the next exec call (same as Android PRoot).
    //   The shared_path directory is also pre-opened for host <-> VM file exchange.
    //
    // Output capture:
    //   We create POSIX pipes for stdin/stdout/stderr and pass the pipe fd numbers
    //   DIRECTLY to wasm_runtime_set_wasi_args_ex.  WAMR stores (or dups) these
    //   fds into its internal WASI fd table, so when TinyEMU calls fd_write(1,…)
    //   the bytes land in our pipe.  After deinstantiate we close the write-ends to
    //   signal EOF to the drain threads.
    //
    // Exit code:
    //   The command is wrapped with a sentinel echo: `echo "__EXIT_$?__"`.
    //   The sentinel is stripped from stdout and the code is extracted.
    //
    // Timeout:
    //   The Wasm call runs on a background thread. A semaphore wait with the
    //   deadline is used; on timeout, wasm_runtime_terminate() signals the VM.
    private func runInVM(command: String, workingDir: String, timeoutMs: Int) -> [String: Any] {
        let maxOutputBytes = 65_536  // matches Android SandboxHandler cap

        let sentinel = "__FLUTTERCLAW_EXIT__"
        let wrappedCommand =
            "cd \(shellEscape(workingDir)) 2>/dev/null || cd /root\n" +
            command + "\n" +
            "echo \"\(sentinel)$?\"\n" +
            "exit 0\n"  // causes the shell (and thus the VM) to exit cleanly

        #if WAMR_AVAILABLE
        return wamrExec(wrappedCommand: wrappedCommand,
                        sentinel: sentinel,
                        timeoutMs: timeoutMs,
                        maxOutputBytes: maxOutputBytes)
        #else
        return [
            "error": true,
            "message": "WAMR xcframework not yet integrated. Run scripts/build-wamr-ios.sh then pod install. sandbox_setup and sandbox_status are functional.",
        ]
        #endif
    }

    #if WAMR_AVAILABLE
    private func wamrExec(wrappedCommand: String,
                          sentinel: String,
                          timeoutMs: Int,
                          maxOutputBytes: Int) -> [String: Any] {

        guard let wasmBytes = try? Data(contentsOf: wasmFileURL()) else {
            return ["error": true, "message": "Failed to read Wasm file."]
        }

        // WASI pre-opened directories.
        // container2wasm's init binary reads preopens from the WASI fd list,
        // serialises them to /mnt/wasi1/info, and bind-mounts each one inside
        // the Alpine guest at the same absolute path.
        //   <documents>/sandbox/root/   → /root   inside Alpine (persistent /root)
        //   <documents>/sandbox/shared/ → shared  inside Alpine (file exchange)
        let rootPath   = rootPersistenceDirectoryURL().path
        let sharedPath = sharedDirectoryURL().path

        // container2wasm's init (running inside TinyEMU) reads WASM argv[0] as the
        // container command to exec.  Pass "/bin/sh" so it runs an Alpine shell.
        // Without this, c2w tries to exec the embedded CMD from the Docker image
        // metadata, which may be missing or wrong → "exec: ... not found" error.
        let argv: [String] = ["/bin/sh"]
        let dirs: [String] = [rootPath, sharedPath]
        let envs: [String] = ["TERM=xterm-256color", "HOME=/root",
                               "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]

        var stdoutData = Data()
        var stderrData = Data()
        var timedOut      = false
        var loadError     = ""
        var execOk        = false
        var execException = ""

        // wasm_runtime_load takes a mutable uint8_t* (it may patch the buffer).
        var mutableWasm = wasmBytes
        mutableWasm.withUnsafeMutableBytes { (rawPtr: UnsafeMutableRawBufferPointer) in
            guard let base = rawPtr.baseAddress else { loadError = "Nil Wasm buffer"; return }

            if !Self.runtimeInitialised {
                _ = wasm_runtime_init()
                Self.runtimeInitialised = true
            }

            var errBuf = [CChar](repeating: 0, count: 256)
            guard let module = wasm_runtime_load(
                base.assumingMemoryBound(to: UInt8.self),
                UInt32(wasmBytes.count),
                &errBuf, UInt32(errBuf.count)
            ) else {
                loadError = String(cString: errBuf)
                return
            }
            defer { wasm_runtime_unload(module) }

            var cArgv = argv.map { strdup($0) }
            var cDirs = dirs.map { strdup($0) }
            var cEnvs = envs.map { strdup($0) }
            defer {
                cArgv.forEach { free($0) }
                cDirs.forEach { free($0) }
                cEnvs.forEach { free($0) }
            }

            // --- I/O pipes ---
            // stdin:  write command then close write-end → EOF after command.
            // stdout/stderr: drain threads read concurrently to prevent pipe-full deadlock.
            //
            // We pass the pipe fd numbers DIRECTLY to wasm_runtime_set_wasi_args_ex
            // so WAMR stores them (and internally dups them) in its WASI fd table.
            // TinyEMU's fd_write(1, …) calls then land in our outPipe.
            // We do NOT dup2 process fd 0/1/2 — no global fd redirect needed.
            var inPipe  = [Int32](repeating: 0, count: 2)
            var outPipe = [Int32](repeating: 0, count: 2)
            var errPipe = [Int32](repeating: 0, count: 2)
            pipe(&inPipe)
            pipe(&outPipe)
            pipe(&errPipe)

            let commandInput = (wrappedCommand + "\n").data(using: .utf8)!
            commandInput.withUnsafeBytes { ptr in
                _ = write(inPipe[1], ptr.baseAddress!, commandInput.count)
            }
            // Do NOT close inPipe[1] here.
            // The Linux serial console inside TinyEMU is a real tty device.
            // If the write-end of stdin closes before the VM's /bin/sh has
            // started (i.e., during the ~15-60s kernel boot), the VM exits
            // immediately with no output.  Instead we rely on "exit 0" at the
            // end of the command script to shut the shell down cleanly, which
            // in turn shuts the VM down.  We close inPipe[1] after deinstantiate.

            // Pass explicit pipe fds so WAMR maps WASI stdin/stdout/stderr to them.
            var constDirs = cDirs.map { UnsafePointer($0) }
            var constEnvs = cEnvs.map { UnsafePointer($0) }
            cArgv.withUnsafeMutableBufferPointer { ab in
            constDirs.withUnsafeMutableBufferPointer { db in
            constEnvs.withUnsafeMutableBufferPointer { eb in
                wasm_runtime_set_wasi_args_ex(
                    module,
                    db.baseAddress, UInt32(dirs.count),
                    nil, 0,
                    eb.baseAddress, UInt32(envs.count),
                    ab.baseAddress, Int32(argv.count),
                    Int64(inPipe[0]),   // stdin  = pipe read-end
                    Int64(outPipe[1]),  // stdout = pipe write-end
                    Int64(errPipe[1])   // stderr = pipe write-end
                )
            }}}

            guard let instance = wasm_runtime_instantiate(
                module,
                1024 * 1024,       // stack: 1MB (c2w TinyEMU needs deep call stacks)
                16 * 1024 * 1024,  // heap: 16MB (WAMR internal allocator)
                &errBuf, UInt32(errBuf.count)
            ) else {
                close(inPipe[0])
                close(outPipe[0]); close(outPipe[1])
                close(errPipe[0]); close(errPipe[1])
                loadError = String(cString: errBuf)
                return
            }

            // Start drainer threads BEFORE the VM runs so they consume data in
            // real time and prevent the pipe buffer from filling up (deadlock).
            let drainGroup = DispatchGroup()
            drainGroup.enter()
            DispatchQueue.global(qos: .utility).async {
                stdoutData = wasmDrainPipe(outPipe[0], max: maxOutputBytes)
                drainGroup.leave()
            }
            drainGroup.enter()
            DispatchQueue.global(qos: .utility).async {
                stderrData = wasmDrainPipe(errPipe[0], max: maxOutputBytes)
                drainGroup.leave()
            }

            // Run the Wasm module on its own thread so we can enforce timeout.
            let runSema = DispatchSemaphore(value: 0)
            let deadline = DispatchTime.now() + .milliseconds(timeoutMs)

            DispatchQueue.global(qos: .userInitiated).async {
                // Each host thread that calls into WAMR must have its signal
                // environment initialised (trap handling for stack overflow,
                // out-of-bounds memory, etc.).  The thread that called
                // wasm_runtime_init() gets this automatically, but GCD worker
                // threads do not.
                _ = wasm_runtime_init_thread_env()
                defer { wasm_runtime_destroy_thread_env() }

                var execArgv = cArgv
                execArgv.withUnsafeMutableBufferPointer { buf in
                    execOk = wasm_application_execute_main(instance, Int32(argv.count), buf.baseAddress)
                }
                if !execOk, let ex = wasm_runtime_get_exception(instance) {
                    execException = String(cString: ex)
                }
                runSema.signal()
            }

            let waitResult = runSema.wait(timeout: deadline)
            if waitResult == .timedOut {
                timedOut = true
                wasm_runtime_terminate(instance)
                _ = runSema.wait(timeout: DispatchTime.now() + .seconds(5))
            }

            // EOF signalling to drain threads:
            //   1. deinstantiate → WAMR closes its dup'd copies of the pipe fds
            //   2. close our own write-end references → drain threads receive EOF
            wasm_runtime_deinstantiate(instance)
            close(inPipe[0])
            close(inPipe[1])  // close AFTER deinstantiate (keep open during boot)
            close(outPipe[1])
            close(errPipe[1])

            drainGroup.wait()
        }

        if !loadError.isEmpty {
            return ["error": true, "message": "WAMR load error: \(loadError)"]
        }
        if timedOut {
            return ["exit_code": -1, "stdout": "", "stderr": "Command timed out.", "timed_out": true]
        }

        // TinyEMU's serial console uses \r\n line endings (standard tty).
        // Strip \r before any further processing.
        var stdoutStr = (String(data: stdoutData, encoding: .utf8) ?? "")
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")
        let stderrStr = (String(data: stderrData, encoding: .utf8) ?? "")
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")

        // Strip the TinyEMU noise from stdout:
        //
        //   The Linux serial console is a real tty device inside TinyEMU.
        //   When /bin/sh reads stdin (our piped commands), the tty line
        //   discipline echoes every character back to stdout (the UART).
        //   ash also prints a shell prompt before each command.  So the raw
        //   stdout contains:
        //
        //     [PREAMBLE]  raw echo of all stdin chars — before first prompt
        //     ~ # cd /root         prompt line (working dir + " # " + cmd)
        //     ~ # echo hello       prompt line
        //     hello                ← actual command output  (KEEP)
        //     /tmp # echo sentinel prompt line
        //     __FLUTTERCLAW_EXIT__0 ← sentinel              (KEEP)
        //     /tmp # exit 0        prompt line
        //
        //   We discard the PREAMBLE and all prompt lines, keeping only the
        //   interleaved command outputs.
        stdoutStr = stripTinyEMUNoise(stdoutStr)

        // Extract sentinel exit code and strip it from stdout.
        // After stripTinyEMUNoise the sentinel appears on its own line.
        var exitCode = 0
        var sentinelFound = false
        if let range = stdoutStr.range(of: sentinel) {
            sentinelFound = true
            let rest = stdoutStr[range.upperBound...].trimmingCharacters(in: .whitespacesAndNewlines)
            exitCode = Int(rest.components(separatedBy: .newlines).first ?? "0") ?? 0
            stdoutStr = String(stdoutStr[..<range.lowerBound])
        }

        var out: [String: Any] = [
            "exit_code": exitCode,
            "stdout": stdoutStr,
            "stderr": stderrStr,
            "timed_out": false,
            // DEBUG — remove before merge
            "_debug_stdout_bytes": stdoutData.count,
            "_debug_stderr_bytes": stderrData.count,
            "_debug_sentinel_found": sentinelFound ? "yes" : "no",
            "_debug_raw_stdout_preview": String(data: stdoutData.prefix(200), encoding: .utf8) ?? "(non-utf8)",
            "_debug_exec_ok": execOk,
            "_debug_exec_exception": execException,
        ]
        if stdoutData.count >= maxOutputBytes { out["stdout_truncated"] = true }
        if stderrData.count >= maxOutputBytes { out["stderr_truncated"] = true }
        return out
    }

    #endif

    private func shellEscape(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Paths

    func wasmFileURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("alpine-ios-sandbox.wasm")
    }

    func sharedDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("shared")
    }

    // Persistent /root/ for the Alpine guest.
    // Mounted via WAMR --dir + container2wasm virtio-9p at the same absolute path
    // inside the VM, so files written to /root/ inside Alpine survive across calls.
    func rootPersistenceDirectoryURL() -> URL {
        sandboxDirectoryURL().appendingPathComponent("root")
    }

    func sandboxDirectoryURL() -> URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("sandbox")
    }
}

// MARK: - TinyEMU output post-processing

// Strip the UART echo preamble and ash shell-prompt lines from TinyEMU stdout.
//
// Raw TinyEMU stdout structure (serial console / tty echo):
//
//   [preamble] echo of all stdin chars (before shell is ready)
//   ~ # cmd1          ← ash prompt + command
//   output1           ← kept
//   /tmp # cmd2       ← ash prompt (workdir changed)
//   output2           ← kept
//   ...
//
// Prompt lines are identified by: starts with "~" or "/" and contains " # "
// with no space in the working-directory portion (e.g. "~ # " or "/tmp # ").
//
// Limitation: output lines that happen to match the prompt pattern (e.g. a
// line like "/bin # something") will be incorrectly stripped.  This is
// acceptable for typical command output.
private func stripTinyEMUNoise(_ raw: String) -> String {
    let lines = raw.components(separatedBy: "\n")
    var pastPreamble = false
    var result: [String] = []

    for line in lines {
        if isTinyEMUPromptLine(line) {
            pastPreamble = true
            // Skip prompt lines.
        } else if pastPreamble {
            result.append(line)
        }
        // Skip preamble lines (before first prompt).
    }
    return result.joined(separator: "\n")
}

// Returns true if `line` looks like an ash prompt: starts with "~" or "/"
// and contains " # " with no spaces before the " # ".
private func isTinyEMUPromptLine(_ line: String) -> Bool {
    guard line.hasPrefix("~") || line.hasPrefix("/") else { return false }
    guard let hashRange = line.range(of: " # ") else { return false }
    let workingDir = String(line[..<hashRange.lowerBound])
    return !workingDir.contains(" ")
}

// MARK: - SHA256

import CommonCrypto

private func sha256Hex(_ data: Data) -> String {
    var digest = [UInt8](repeating: 0, count: Int(CC_SHA256_DIGEST_LENGTH))
    data.withUnsafeBytes { CC_SHA256($0.baseAddress, CC_LONG(data.count), &digest) }
    return digest.map { String(format: "%02x", $0) }.joined()
}

// MARK: - Helpers

// Drain a pipe read-fd into a Data buffer, capped at `max` bytes.
// Reads until EOF (write end closed) or cap reached. Closes the fd when done.
private func wasmDrainPipe(_ fd: Int32, max: Int) -> Data {
    var data = Data()
    var buf  = [UInt8](repeating: 0, count: 4096)
    while data.count < max {
        let n = read(fd, &buf, min(buf.count, max - data.count))
        if n <= 0 { break }
        data.append(contentsOf: buf[..<n])
    }
    close(fd)
    return data
}

// MARK: - Errors

private enum SandboxError: LocalizedError {
    case invalidURL
    case downloadFailed(Int)
    case sha256Mismatch(expected: String, got: String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid Wasm download URL."
        case .downloadFailed(let code):
            return "Failed to download Alpine Wasm image (HTTP \(code))."
        case .sha256Mismatch(let expected, let got):
            return "Wasm image SHA256 mismatch. Expected \(expected), got \(got)."
        }
    }
}
